version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-vector
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web interface
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local
